# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
