# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20161106_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../media/default-user.png', upload_to=''),
        ),
    ]
