# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_auto_20161106_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voted_down_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_disapproved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='voted_up_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
