# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_auto_20161110_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='approved_by',
            field=models.ManyToManyField(null=True, related_name='answers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='disapproved_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='disapproved_by',
            field=models.ManyToManyField(null=True, related_name='answers_disapproved', to=settings.AUTH_USER_MODEL),
        ),
    ]
