# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_auto_20161111_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='questions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='questions_disapproved', to=settings.AUTH_USER_MODEL),
        ),
    ]
