# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 15:50
from __future__ import unicode_literals
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0019_auto_20161112_1018'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX question_header_index ON polls_question (header, content)',),
            ('DROP INDEX question_header_index on polls_question',)
        ),
    ]
